# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QassessmentWizard
                                 A QGIS plugin
 Wizard to evaluation assessment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-16
        copyright            : (C) 2025 by David Torres
        email                : davidt1987@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QassessmentWizard class from file QassessmentWizard.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .assessment_wizard import QassessmentWizard
    return QassessmentWizard(iface)
