# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QassessmentWizardDialog
                                 A QGIS plugin
 Wizard to evaluation assessment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-16
        git sha              : $Format:%H$
        copyright            : (C) 2025 by David Torres
        email                : davidt1987@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsProject

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'assessment_wizard_dialog_base.ui'))


class QassessmentWizardDialog(QtWidgets.QWizard, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(QassessmentWizardDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Initialize wizard pages
        self.initialize_page_1()
        self.initialize_page_2()
        self.initialize_page_3()

    def initialize_page_1(self):
        """Initialize the first wizard page."""
        # Page 1 contains name and description fields
        # Access them using:
        # - self.lineEdit_name
        # - self.textEdit_description
        # - self.listWidget_layers

        # Populate the layer list with available layers from QGIS
        self.populate_layers()

    def populate_layers(self):
        """Populate the list widget with available layers from the QGIS project."""
        self.listWidget_layers.clear()

        # Get all layers from the current QGIS project
        layers = QgsProject.instance().mapLayers().values()

        # Add each layer to the list widget
        for layer in layers:
            self.listWidget_layers.addItem(layer.name())

    def get_selected_layers(self):
        """Get the list of selected layer names."""
        selected_items = self.listWidget_layers.selectedItems()
        return [item.text() for item in selected_items]

    def initialize_page_2(self):
        """Initialize the second wizard page."""
        # Add your page 2 initialization logic here
        pass

    def initialize_page_3(self):
        """Initialize the third wizard page."""
        # Add your page 3 initialization logic here
        pass
